import {appImages} from '../assets';

export const jobs = [
  {
    id: '1',
    name: 'Product Designer',
    location: 'Chicago, USA',
    time: '1 day ago',
    company: 'KMPS',
  },
  {
    id: '2',
    name: 'Software Engineer',
    location: 'San Francisco, USA',
    time: '2 days ago',
    company: 'Tech Innovations',
  },
  {
    id: '3',
    name: 'Marketing Manager',
    location: 'New York City, USA',
    time: '3 days ago',
    company: 'Global Marketing Solutions',
  },
  {
    id: '4',
    name: 'Data Analyst',
    location: 'London, UK',
    time: '4 days ago',
    company: 'Data Insights Ltd.',
  },
  {
    id: '5',
    name: 'Frontend Developer',
    location: 'Berlin, Germany',
    time: '5 days ago',
    company: 'WebTech Solutions',
  },
  {
    id: '6',
    name: 'HR Specialist',
    location: 'Tokyo, Japan',
    time: '6 days ago',
    company: 'HR Pros',
  },
  {
    id: '7',
    name: 'Financial Analyst',
    location: 'Sydney, Australia',
    time: '1 week ago',
    company: 'Finance Plus',
  },
  {
    id: '8',
    name: 'Graphic Designer',
    location: 'Paris, France',
    time: '1 week ago',
    company: 'Creative Minds',
  },
  {
    id: '9',
    name: 'Content Writer',
    location: 'Toronto, Canada',
    time: '2 weeks ago',
    company: 'Content Creations Inc.',
  },
  {
    id: '10',
    name: 'UI/UX Designer',
    location: 'Singapore',
    time: '2 weeks ago',
    company: 'Design Innovations',
  },
];

export const currentJobs = [
  {
    id: 1,
    start_at: new Date(),
    end_at: new Date(),
    estimator: 'Adam Smith',
    paymentBy: 'Customer',
    status: 'Pending',
    company: 'Tech Solutions',
    QC: 'Alice Johnson',
  },
  {
    id: 2,
    start_at: new Date(),
    end_at: new Date(),
    estimator: 'Haris',
    paymentBy: 'Supplier',
    status: 'Completed',
    company: 'Innovative Corp',
    QC: 'Bob Martin',
  },
  {
    id: 3,
    start_at: new Date(),
    end_at: new Date(),
    estimator: 'John Doe',
    paymentBy: 'Customer',
    status: 'In-Progress',
    company: 'Future Enterprises',
    QC: 'Charlie Brown',
  },
  {
    id: 4,
    start_at: new Date(),
    end_at: new Date(),
    estimator: 'Jane Roe',
    paymentBy: 'Supplier',
    status: 'Pending',
    company: 'Global Tech',
    QC: 'David Clark',
  },
  {
    id: 5,
    start_at: new Date(),
    end_at: new Date(),
    estimator: 'Alex Johnson',
    paymentBy: 'Customer',
    status: 'Completed',
    company: 'Visionary Solutions',
    QC: 'Eve Davis',
  },
  {
    id: 6,
    start_at: new Date(),
    end_at: new Date(),
    estimator: 'Emily Davis',
    paymentBy: 'Customer',
    status: 'In-Progress',
    company: 'NextGen Innovators',
    QC: 'Frank Harris',
  },
  {
    id: 7,
    start_at: new Date(),
    end_at: new Date(),
    estimator: 'Michael Brown',
    paymentBy: 'Supplier',
    status: 'Pending',
    company: 'Alpha Tech',
    QC: 'Grace Lee',
  },
  {
    id: 8,
    start_at: new Date(),
    end_at: new Date(),
    estimator: 'Jessica Williams',
    paymentBy: 'Customer',
    status: 'Completed',
    company: 'Tech Pioneers',
    QC: 'Henry King',
  },
  {
    id: 9,
    start_at: new Date(),
    end_at: new Date(),
    estimator: 'David Wilson',
    paymentBy: 'Supplier',
    status: 'In-Progress',
    company: 'Synergy Solutions',
    QC: 'Isabella Moore',
  },
  {
    id: 10,
    start_at: new Date(),
    end_at: new Date(),
    estimator: 'Sophia Martinez',
    paymentBy: 'Customer',
    status: 'Pending',
    company: 'Quantum Innovations',
    QC: 'Jack Wilson',
  },
];

export const pastJobs = [
  {
    id: 1,
    start_at: new Date('2023-01-10T09:00:00'),
    end_at: new Date('2023-01-10T17:00:00'),
    estimator: 'Adam Smith',
    paymentBy: 'Customer',
    status: 'Completed',
    company: 'Tech Solutions',
    QC: 'Alice Johnson',
  },
  {
    id: 2,
    start_at: new Date('2023-02-05T08:30:00'),
    end_at: new Date('2023-02-05T16:30:00'),
    estimator: 'Haris',
    paymentBy: 'Supplier',
    status: 'Completed',
    company: 'Innovative Corp',
    QC: 'Bob Martin',
  },
  {
    id: 3,
    start_at: new Date('2023-03-12T10:00:00'),
    end_at: new Date('2023-03-12T18:00:00'),
    estimator: 'John Doe',
    paymentBy: 'Customer',
    status: 'Completed',
    company: 'Future Enterprises',
    QC: 'Charlie Brown',
  },
  {
    id: 4,
    start_at: new Date('2023-04-08T09:30:00'),
    end_at: new Date('2023-04-08T17:30:00'),
    estimator: 'Jane Roe',
    paymentBy: 'Supplier',
    status: 'Completed',
    company: 'Global Tech',
    QC: 'David Clark',
  },
  {
    id: 5,
    start_at: new Date('2023-05-15T11:00:00'),
    end_at: new Date('2023-05-15T19:00:00'),
    estimator: 'Alex Johnson',
    paymentBy: 'Customer',
    status: 'Completed',
    company: 'Visionary Solutions',
    QC: 'Eve Davis',
  },
  {
    id: 6,
    start_at: new Date('2023-06-20T12:00:00'),
    end_at: new Date('2023-06-20T20:00:00'),
    estimator: 'Emily Davis',
    paymentBy: 'Customer',
    status: 'Completed',
    company: 'NextGen Innovators',
    QC: 'Frank Harris',
  },
  {
    id: 7,
    start_at: new Date('2023-07-18T09:00:00'),
    end_at: new Date('2023-07-18T17:00:00'),
    estimator: 'Michael Brown',
    paymentBy: 'Supplier',
    status: 'Completed',
    company: 'Alpha Tech',
    QC: 'Grace Lee',
  },
  {
    id: 8,
    start_at: new Date('2023-08-22T08:00:00'),
    end_at: new Date('2023-08-22T16:00:00'),
    estimator: 'Jessica Williams',
    paymentBy: 'Customer',
    status: 'Completed',
    company: 'Tech Pioneers',
    QC: 'Henry King',
  },
  {
    id: 9,
    start_at: new Date('2023-09-10T10:00:00'),
    end_at: new Date('2023-09-10T18:00:00'),
    estimator: 'David Wilson',
    paymentBy: 'Supplier',
    status: 'Completed',
    company: 'Synergy Solutions',
    QC: 'Isabella Moore',
  },
  {
    id: 10,
    start_at: new Date('2023-10-15T09:30:00'),
    end_at: new Date('2023-10-15T17:30:00'),
    estimator: 'Sophia Martinez',
    paymentBy: 'Customer',
    status: 'Completed',
    company: 'Quantum Innovations',
    QC: 'Jack Wilson',
  },
];

export const JobBiddingArray = [
  {
    id: '1',
    name: 'Joe Albert',
    bid: 350,
    customer: 'Canal Side Hub',
    rate: 4,
  },
  {
    id: '2',
    name: 'Sara Lin',
    bid: 400,
    customer: 'Urban Green',
    rate: 5,
  },
  {
    id: '3',
    name: 'Mike Jones',
    bid: 300,
    customer: 'Tech Solutions',
    rate: 3,
  },
  {
    id: '4',
    name: 'Emma Brown',
    bid: 450,
    customer: 'Health Pro Clinic',
    rate: 5,
  },
  {
    id: '5',
    name: 'Liam Smith',
    bid: 370,
    customer: 'Creative Minds',
    rate: 4,
  },
  {
    id: '6',
    name: 'Olivia White',
    bid: 320,
    customer: 'Fitness World',
    rate: 4,
  },
  {
    id: '7',
    name: 'Noah Johnson',
    bid: 380,
    customer: 'Bright Future School',
    rate: 3,
  },
  {
    id: '8',
    name: 'Ava Williams',
    bid: 410,
    customer: 'Eco Friendly Co.',
    rate: 5,
  },
  {
    id: '9',
    name: 'Lucas Brown',
    bid: 330,
    customer: 'Digital Innovators',
    rate: 4,
  },
  {
    id: '10',
    name: 'Mia Martinez',
    bid: 390,
    customer: 'Foodies Hub',
    rate: 4,
  },
  {
    id: '11',
    name: 'Ethan Davis',
    bid: 360,
    customer: 'Travel Experts',
    rate: 4,
  },
];

export const notificationsArray = [
  {
    id: 1,
    title: 'New Message',
    description: 'You have received a new message from John.',
    icon: 'message',
    iconColor: '#28C76F',
    read: false,
  },
  {
    id: 2,
    title: 'Update Available',
    description:
      'A new update is available for your application. you should update your application to enjoy new features',
    icon: 'update',
    iconColor: '#007bff',
    read: false,
  },
  {
    id: 3,
    title: 'Friend Request',
    description: 'Anna has sent you a friend request.',
    icon: 'account-plus',
    iconColor: '#fd7e14',
    read: true,
  },
  {
    id: 4,
    title: 'Reminder',
    description: "Don't forget your meeting at 3 PM.",
    icon: 'bell',
    iconColor: '#dc3545',
    read: false,
  },
  {
    id: 5,
    title: 'Promotion',
    description: 'Get 50% off on your next purchase.',
    icon: 'tag',
    iconColor: '#fd7e14',
    read: true,
  },
];

export const chatsArray = [
  {
    id: 1,
    time: '2024-05-20T13:24:04.661Z',
    userName: 'Alice',
    image: appImages?.Logo,
    recentMessage: 'Hey, how are you?',
    read: false,
  },
  {
    id: 2,
    time: '2024-05-20T13:24:04.661Z',
    userName: 'Bob',
    image: appImages?.Logo,
    recentMessage: 'I just saw that movie you recommended!',
    read: true,
  },
  {
    id: 3,
    time: '2024-05-20T13:24:04.661Z',
    userName: 'Charlie',
    image: appImages?.Logo,
    recentMessage: 'Let’s meet this weekend!',
    read: false,
  },
  {
    id: 4,
    time: '2024-05-20T13:24:04.661Z',
    userName: 'David',
    image: appImages?.Logo,
    recentMessage: 'Can you send me that document?',
    read: true,
  },
  {
    id: 5,
    time: '2024-05-20T13:24:04.661Z',
    userName: 'Eve',
    image: appImages?.Logo,
    recentMessage: 'Check out this funny meme!',
    read: false,
  },
];
